---
- name: Create Consumer Replica Entry
  community.general.ldap_entry:
    server_uri: "{{ dirsrv_server_uri }}"
    validate_certs: "{{ dirsrv_tls_certificate_trusted }}"
    start_tls: "{{ dirsrv_use_starttls }}"
    bind_dn: "{{ dirsrv_rootdn }}"
    bind_pw: "{{ dirsrv_rootdn_password }}"
    dn: "cn=replica,cn=\"{{ dirsrv_suffix }}\",cn=mapping tree,cn=config"
    objectClass:
      - top
      - nsds5replica
      - extensibleObject
    attributes:
      cn: "replica"
      # MUST attributes, cannot add them later
      nsds5replicaroot: "{{ dirsrv_suffix }}"
      nsds5replicaid: "65535"
      nsds5replicatype: "2"  # not a MUST but cannot be changed. Ever. Overwriting with the same value triggers an error.
    state: present

- name: Configure Consumer Replica Entry
  community.general.ldap_attrs:
    server_uri: "{{ dirsrv_server_uri }}"
    validate_certs: "{{ dirsrv_tls_certificate_trusted }}"
    start_tls: "{{ dirsrv_use_starttls }}"
    bind_dn: "{{ dirsrv_rootdn }}"
    bind_pw: "{{ dirsrv_rootdn_password }}"
    dn: "cn=replica,cn=\"{{ dirsrv_suffix }}\",cn=mapping tree,cn=config"
    state: exact
    attributes:
      nsds5replicaroot: "{{ dirsrv_suffix }}"
      nsds5ReplicaBindDN: "cn={{ dirsrv_replication_user }},cn=config"
      nsds5flags: "0"  # 0 = does not write to changelog = is a consumer

- name: Configure referral
  community.general.ldap_attrs:
    server_uri: "{{ dirsrv_server_uri }}"
    validate_certs: "{{ dirsrv_tls_certificate_trusted }}"
    start_tls: "{{ dirsrv_use_starttls }}"
    bind_dn: "{{ dirsrv_rootdn }}"
    bind_pw: "{{ dirsrv_rootdn_password }}"
    dn: "cn=\"{{ dirsrv_suffix }}\",cn=mapping tree,cn=config"
    state: exact
    attributes:
      nsslapd-referral: "{{ dirsrv_consumer_referral_to_supplier | urlsplit('scheme') }}://\
    {{ dirsrv_consumer_referral_to_supplier | urlsplit('netloc') }}\
    /{{ dirsrv_suffix | replace('\"', '\\\"') | replace(',', '\\,') }}"
      nsslapd-state: "referral on update"
