---
# From the Administration Guide:
#
# When setting up replication agreements, first set them up between all suppliers, then between the
# suppliers and the hubs, and last between the hub and the consumers.

- name: Set agreement name
  set_fact:
    dirsrv_agreement_cn: "agreement_with_{{ dirsrv_consumer_uri | urlsplit('hostname') | replace('.', '_') }}"

# Add only to supplier, one for each consumer
- name: "Add replication agreement with {{ dirsrv_consumer_uri | urlsplit('netloc') }} on supplier"
  ldap_entry:
    server_uri: "{{ dirsrv_server_uri }}"
    validate_certs: "{{ dirsrv_tls_certificate_trusted }}"
    start_tls: "{{ dirsrv_use_starttls }}"
    bind_dn: "{{ dirsrv_rootdn }}"
    bind_pw: "{{ dirsrv_rootdn_password }}"
    dn: "cn={{ dirsrv_agreement_cn }},cn=replica,cn=\"{{ dirsrv_suffix  }}\",cn=mapping tree,cn=config"
    objectClass:
      - top
      - nsds5ReplicationAgreement
    attributes:
      cn: "{{ dirsrv_agreement_cn }}"
      # these attributes cannot be modified once set, anyway
      nsds5ReplicaHost: "{{ dirsrv_consumer_uri | urlsplit('hostname') }}"
      nsds5ReplicaTransportInfo: "{{ 'SSL' if ( dirsrv_consumer_uri | urlsplit('scheme') | lower ) == 'ldaps' else 'TLS' }}"  # SSL = LDAPS, TLS = StartTLS.
      # These ones... can, I think? However, adding the entry fails if they're not present
      nsds5replicaport: "{{ '389' if not dirsrv_consumer_uri|urlsplit('port') else dirsrv_consumer_uri|urlsplit('port') }}"
      nsds5ReplicaBindDN: "cn={{ dirsrv_replication_user_remote | default(dirsrv_replication_user) }},cn=config"
      nsds5ReplicaCredentials: "{{ dirsrv_replication_user_password_remote | default(dirsrv_replication_user_password) }}"
      nsds5replicabindmethod: "{{ dirsrv_replica_bind_method }}"
      nsds5replicaroot: "{{ dirsrv_suffix }}"
      description: "Agreement between this server (supplier) and {{ dirsrv_consumer_uri }} (consumer). Managed by Ansible."
      nsds5replicatedattributelist: "{{ dirsrv_replica_attributes_list }}"
      nsds5ReplicatedAttributeListTotal: "{{ dirsrv_replica_attributes_list_total }}"
      nsds5ReplicaEnabled: "{{ 'on' if dirsrv_begin_replication_immediately else 'off' }}"
    state: present

- name: Configure replication agreement on supplier
  ldap_attr:
    server_uri: "{{ dirsrv_server_uri }}"
    validate_certs: "{{ dirsrv_tls_certificate_trusted }}"
    start_tls: "{{ dirsrv_use_starttls }}"
    bind_dn: "{{ dirsrv_rootdn }}"
    bind_pw: "{{ dirsrv_rootdn_password }}"
    dn: "cn={{ dirsrv_agreement_cn }},cn=replica,cn=\"{{ dirsrv_suffix  }}\",cn=mapping tree,cn=config"
    name: "{{ item.name }}"
    values: "{{ item.value }}"
    state: exact
  loop:
    - { name: "nsds5replicaport", value: "{{ '389' if not dirsrv_consumer_uri|urlsplit('port') else dirsrv_consumer_uri|urlsplit('port') }}" }
    - { name: "nsds5ReplicaBindDN", value: "cn={{ dirsrv_replication_user_remote | default(dirsrv_replication_user) }},cn=config" }
    - { name: "nsds5replicabindmethod", value: "{{ dirsrv_replica_bind_method }}" }
    - { name: "nsds5replicaroot", value: "{{ dirsrv_suffix }}" }
    - { name: "description", value: "Agreement between this server (supplier) and {{ dirsrv_consumer_uri }} (consumer). Managed by Ansible." }
    - { name: "nsds5replicatedattributelist", value: "{{ dirsrv_replica_attributes_list }}" }
    - { name: "nsds5ReplicatedAttributeListTotal", value: "{{ dirsrv_replica_attributes_list_total }}" }

# The exact same as above, but with "changed_when: false" because that "changed" annoyed me.
# The downside is that if password actually changes, you'll see that nothing has changed according to Ansible, but it did work.
- name: Configure password on replication agreement on supplier
  ldap_attr:
    server_uri: "{{ dirsrv_server_uri }}"
    validate_certs: "{{ dirsrv_tls_certificate_trusted }}"
    start_tls: "{{ dirsrv_use_starttls }}"
    bind_dn: "{{ dirsrv_rootdn }}"
    bind_pw: "{{ dirsrv_rootdn_password }}"
    dn: "cn={{ dirsrv_agreement_cn }},cn=replica,cn=\"{{ dirsrv_suffix }}\",cn=mapping tree,cn=config"
    name: "nsds5ReplicaCredentials"
    values: "{{ dirsrv_replication_user_password_remote | default(dirsrv_replication_user_password) }}"
    state: exact
  changed_when: false

# nsds5replicaupdateschedule can be used to "pause" replication (see Configuration and other stuff Reference), nice
